##################################
# Configuration Properties File  #
##################################

# PATH
test_plan=test_plan/MAYA-Student-v9.jmx
#test_plan=test_plan/MAYA_Login_Test_v5.jmx
student_data=test_data/student_data.csv

# Backend Listener Settings
runId=STE010
bucket=students

# Student Thread Settings (total across all slaves)
student=15000
rampUp=300
loop=1
thinkTime=3000

smoke=false
logout=true

# Dynatrace Settings
dynatrace.tsn=MAYA-Student
dynatrace.lsn=CE-01-Enrolment

# Report Settings
# Filter username transaction labels from report (when using ${USERNAME} as TC name)
filter_usernames=true

