"""Manage a custom JMeter reportgenerator properties file.

Creates and maintains ``webapp/config/report.properties`` which is loaded
via ``jmeter -q <path>`` at report-generation time.  The file overrides
JMeter's built-in ``reportgenerator.properties`` without touching the
original installation.

Mechanism verified on JMeter 5.6.3:
  Setting ``jmeter.reportgenerator.graph.<id>.classname=`` (empty) causes
  JMeter to emit ``data: {}`` for that graph, effectively disabling it.
"""

import re
from pathlib import Path

from services.config_parser import read_config_properties

APP_DIR = Path(__file__).resolve().parent.parent
PROPERTIES_FILE = APP_DIR / "config" / "report.properties"

# ── All 16 default graphs in JMeter 5.6.3 ──────────────────────────────
# Each tuple: (graph_id, title, category, default_enabled)
#   category: "overtime" = heavy (one data-point per granularity per sampler)
#             "summary"  = lightweight aggregate
GRAPHS = [
    ("activeThreadsOverTime",              "Active Threads Over Time",                         "overtime", True),
    ("responseTimesOverTime",              "Response Time Over Time",                          "overtime", True),
    ("responseTimePercentilesOverTime",    "Response Time Percentiles Over Time",              "overtime", True),
    ("latenciesOverTime",                  "Latencies Over Time",                              "overtime", True),
    ("connectTimeOverTime",               "Connect Time Over Time",                            "overtime", True),
    ("bytesThroughputOverTime",           "Bytes Throughput Over Time",                        "overtime", True),
    ("hitsPerSecond",                      "Hits Per Second",                                  "overtime", True),
    ("codesPerSecond",                     "Codes Per Second",                                 "overtime", True),
    ("transactionsPerSecond",             "Transactions Per Second",                           "overtime", True),
    ("totalTPS",                           "Total Transactions Per Second",                    "overtime", True),
    ("responseTimePercentiles",           "Response Time Percentiles",                         "summary", True),
    ("responseTimeDistribution",          "Response Time Distribution",                        "summary", True),
    ("syntheticResponseTimeDistribution", "Synthetic Response Times Distribution",             "summary", True),
    ("timeVsThreads",                     "Time VS Threads",                                   "summary", True),
    ("responseTimeVsRequest",             "Response Time Vs Request",                          "summary", True),
    ("latencyVsRequest",                  "Latencies Vs Request",                              "summary", True),
]

GRAPH_IDS = [g[0] for g in GRAPHS]
OVERTIME_IDS = [g[0] for g in GRAPHS if g[2] == "overtime"]

DEFAULT_GRANULARITY = 60000


def _defaults() -> dict:
    """Return default settings (all graphs enabled)."""
    return {
        "granularity": DEFAULT_GRANULARITY,
        "graphs": {gid: True for gid in GRAPH_IDS},
    }


def load() -> dict:
    """Load current report settings from the properties file.

    If the file doesn't exist, returns defaults (all graphs enabled).
    """
    settings = _defaults()
    props = read_config_properties(PROPERTIES_FILE)

    gran = props.get("jmeter.reportgenerator.overall_granularity")
    if gran:
        try:
            settings["granularity"] = int(gran)
        except ValueError:
            pass

    for key, value in props.items():
        if key.endswith(".classname") and value == "":
            parts = key.split(".")
            if len(parts) == 5 and parts[2] == "graph":
                gid = parts[3]
                if gid in settings["graphs"]:
                    settings["graphs"][gid] = False

    return settings


def save(settings: dict) -> None:
    """Write report.properties based on the given settings dict."""
    PROPERTIES_FILE.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Auto-generated by webapp — do not edit manually.",
        "# Loaded via: jmeter -q <this file>",
        "",
    ]

    # Granularity
    gran = settings.get("granularity", DEFAULT_GRANULARITY)
    lines.append(f"jmeter.reportgenerator.overall_granularity={gran}")
    lines.append("")

    # Disabled graphs — override classname to empty
    graphs = settings.get("graphs", {})
    disabled = [gid for gid in GRAPH_IDS if not graphs.get(gid, True)]
    if disabled:
        lines.append("# Disabled graphs (empty classname = excluded from report)")
        for gid in disabled:
            lines.append(f"jmeter.reportgenerator.graph.{gid}.classname=")
        lines.append("")

    with open(PROPERTIES_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def get_properties_file_path() -> Path:
    """Return the absolute path to report.properties, creating defaults if needed."""
    if not PROPERTIES_FILE.exists():
        save(_defaults())
    return PROPERTIES_FILE


def get_properties_args() -> list[str]:
    """Return JMeter CLI args to load the custom properties file."""
    return ["-q", str(get_properties_file_path())]


def graph_metadata() -> list[dict]:
    """Return graph metadata for the Settings UI."""
    return [
        {"id": gid, "title": title, "category": cat, "default_enabled": default}
        for gid, title, cat, default in GRAPHS
    ]


def disabled_graph_ids() -> list[str]:
    """Return list of currently disabled graph IDs."""
    settings = load()
    graphs = settings.get("graphs", {})
    return [gid for gid in GRAPH_IDS if not graphs.get(gid, True)]


def _remove_portlet_div(html: str, gid: str) -> str:
    """Remove a <div class="col-lg-12 portlet" id="gid">...</div> block.

    Uses div nesting depth to find the correct closing </div>, since
    JMeter's report templates use inconsistent comment markers.
    """
    pattern = rf'<div\s[^>]*\bportlet\b[^>]*\bid="{re.escape(gid)}"[^>]*>'
    m = re.search(pattern, html)
    if not m:
        return html

    start = m.start()
    depth = 0
    i = m.start()
    while i < len(html):
        if html[i:i+4] == '<div':
            depth += 1
            i += 4
        elif html[i:i+6] == '</div>':
            depth -= 1
            if depth == 0:
                end = i + 6
                # Also consume trailing whitespace and optional comment
                rest = html[end:]
                trail = re.match(r'\s*(?:<!--[^>]*-->)?\s*', rest)
                if trail:
                    end += trail.end()
                return html[:start] + html[end:]
            i += 6
        else:
            i += 1
    return html


def cleanup_report_html(report_dir: Path) -> None:
    """Remove disabled graph panels and sidebar links from generated report HTML.

    JMeter still emits the HTML containers even when classname is empty.
    This post-processes the pages to hide those empty sections.
    """
    disabled = disabled_graph_ids()
    if not disabled:
        return

    pages_dir = report_dir / "content" / "pages"
    if not pages_dir.is_dir():
        return

    # Also clean the sidebar links in index.html
    html_files = list(pages_dir.glob("*.html"))
    index_html = report_dir / "index.html"
    if index_html.exists():
        html_files.append(index_html)

    for html_file in html_files:
        try:
            content = html_file.read_text(encoding="utf-8")
            original = content

            for gid in disabled:
                # Remove graph panel div (nested div counting)
                content = _remove_portlet_div(content, gid)

                # Remove sidebar nav links: <li><a href="...#graphId"...>...</a></li>
                content = re.sub(
                    rf'(?s)<li>\s*<a\s+href="[^"]*#{re.escape(gid)}"[^>]*>.*?</a>\s*</li>',
                    '',
                    content,
                )

            # Remove sidebar parent <li> entries whose child <ul> is now empty
            # Handles both nav-third-level (with arrow) and nav-second-level items
            content = re.sub(
                r'(?s)<li>\s*<a[^>]*>[^<]*<span class="fa arrow"></span></a>\s*'
                r'<ul[^>]*>\s*</ul>\s*</li>',
                '',
                content,
            )

            if content != original:
                html_file.write_text(content, encoding="utf-8")
        except Exception:
            continue

    # Remove sidebar links to pages that are now empty (no graph panels left)
    _cleanup_empty_page_links(report_dir, disabled)


# Map: page filename → graph IDs it contains
_PAGE_GRAPHS = {
    "OverTime.html": [
        "responseTimesOverTime", "responseTimePercentilesOverTime",
        "activeThreadsOverTime", "bytesThroughputOverTime",
        "latenciesOverTime", "connectTimeOverTime",
    ],
    "Throughput.html": [
        "hitsPerSecond", "codesPerSecond", "transactionsPerSecond",
        "totalTPS", "responseTimeVsRequest", "latencyVsRequest",
    ],
    "ResponseTimes.html": [
        "responseTimePercentiles", "responseTimeDistribution",
        "syntheticResponseTimeDistribution", "timeVsThreads",
    ],
}


def _cleanup_empty_page_links(report_dir: Path, disabled: list[str]) -> None:
    """Remove sidebar links to pages where ALL graphs have been disabled."""
    disabled_set = set(disabled)
    empty_pages = []
    for page, graph_ids in _PAGE_GRAPHS.items():
        if all(gid in disabled_set for gid in graph_ids):
            empty_pages.append(page)

    if not empty_pages:
        return

    # Clean all HTML files that have sidebars
    html_files = list((report_dir / "content" / "pages").glob("*.html"))
    index_html = report_dir / "index.html"
    if index_html.exists():
        html_files.append(index_html)

    for html_file in html_files:
        try:
            content = html_file.read_text(encoding="utf-8")
            original = content
            for page in empty_pages:
                # Remove <li><a href="...PageName.html">...</a></li>
                content = re.sub(
                    rf'(?s)<li>\s*<a\s+href="[^"]*{re.escape(page)}"[^>]*>.*?</a>\s*</li>',
                    '',
                    content,
                )
            if content != original:
                html_file.write_text(content, encoding="utf-8")
        except Exception:
            continue
